name: camerawesome
description: 'Easiest Flutter camera Plugin with builtin UI. Supporting capturing images, streaming images, video recording, switch sensors, autofocus, flash, filters... on Android and iOS.'
version: 2.5.0
homepage: 'https://Apparence.io'
repository: 'https://github.com/Apparence-io/camera_awesome'
environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=1.10.0'
dependencies:
  carousel_slider: ^5.0.0
  collection: ^1.17.2
  colorfilter_generator: ^0.0.8
  cross_file: ^0.3.3+6
  flutter:
    sdk: flutter
  image: ^4.1.3
  path_provider: ^2.0.8
  rxdart: ^0.27.7
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  pigeon: ^21.1.0
flutter:
  assets:
  - assets/icons/1_1.png
  - assets/icons/16_9.png
  - assets/icons/4_3.png
  - assets/icons/expanded.png
  - assets/icons/minimized.png
  plugin:
    platforms:
      android:
        package: com.apparence.camerawesome.cameraX
        pluginClass: CameraAwesomeX
      ios:
        pluginClass: CamerawesomePlugin
